function fsk_BEP(rx_data,m,flip)
%function fsk_BEP(rx_data,m)
% Estimate the BEP of the data bits recovered
% by the RTL-SDR Based FSK Receiver.
% 
% The reference m-sequence generated in MATLAB
% was found to produce sequences running in the opposite
% direction relative to the m-sequences generated by the
% mbed. To allow error detection the reference m-sequence
% is flipped.
%
% Mark Wickert April 2014

Nbits = length(rx_data);
c = m_seq(m);
if flip == 1,
    % Flip the sequence to compenstate for mbed code difference
    c = fliplr(c);
end
L = ceil(Nbits/length(c));
tx_data = c'*ones(1,L);
tx_data = reshape(tx_data,1,L*length(c));
tx_data = tx_data(1:Nbits);
% Convert to +1/-1 bits
tx_data = 2*tx_data - 1;

[Pe,errors,N_RecBits] = bit_errors(tx_data,rx_data',1);
end

